// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$3 from "./loaders/availableIcons.ts";
import * as $$$4 from "./loaders/extensions/PDPCollectionFlags.ts";
import * as $$$5 from "./loaders/extensions/PDPColorsNew.ts";
import * as $$$6 from "./loaders/extensions/PLPCollectionFlags.ts";
import * as $$$7 from "./loaders/extensions/ProductColorSimilars.ts";
import * as $$$8 from "./loaders/extensions/ProductShelfCollectionsFlags.ts";
import * as $$$9 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$2 from "./loaders/MenuInstitucionalLoader.tsx";
import * as $$$10 from "./loaders/ourStores.ts";
import * as $$$11 from "./loaders/productRecommendations.ts";
import * as $$$12 from "./loaders/productSuggestions.ts";
import * as $$$13 from "./loaders/sizebay.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Benefits.tsx";
import * as $$$$$$2 from "./sections/Cards/CardShowcase.tsx";
import * as $$$$$$3 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$4 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$5 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$6 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$7 from "./sections/Cards/ProductShowcase.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$10 from "./sections/Component.tsx";
import * as $$$$$$11 from "./sections/Content/Banner.tsx";
import * as $$$$$$12 from "./sections/Content/Benefits.tsx";
import * as $$$$$$13 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$14 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$15 from "./sections/Content/Faq.tsx";
import * as $$$$$$16 from "./sections/Content/Features.tsx";
import * as $$$$$$17 from "./sections/Content/Hero.tsx";
import * as $$$$$$18 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$19 from "./sections/Content/Intro.tsx";
import * as $$$$$$20 from "./sections/Content/Logos.tsx";
import * as $$$$$$21 from "./sections/Content/Partners.tsx";
import * as $$$$$$22 from "./sections/Content/RichText.tsx";
import * as $$$$$$23 from "./sections/Content/Table.tsx";
import * as $$$$$$24 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$25 from "./sections/Content/Text.tsx";
import * as $$$$$$26 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$27 from "./sections/Footer.tsx";
import * as $$$$$$28 from "./sections/Footer/Footer.tsx";
import * as $$$$$$29 from "./sections/Gallery.tsx";
import * as $$$$$$30 from "./sections/Header/Header.tsx";
import * as $$$$$$31 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$32 from "./sections/Images/BannerWithLink.tsx";
import * as $$$$$$33 from "./sections/Images/Carousel.tsx";
import * as $$$$$$34 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$35 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$36 from "./sections/Institutional/AboutUs.tsx";
import * as $$$$$$37 from "./sections/Institutional/Breadcrumb.tsx";
import * as $$$$$$38 from "./sections/Institutional/ImageCard.tsx";
import * as $$$$$$39 from "./sections/Institutional/InstitucionalIndiqueForm.tsx";
import * as $$$$$$40 from "./sections/Institutional/InstitucionalPage.tsx";
import * as $$$$$$41 from "./sections/Institutional/InstitucionalPageIframe.tsx";
import * as $$$$$$42 from "./sections/Institutional/InstitucionalThereeImages.tsx";
import * as $$$$$$43 from "./sections/Institutional/Institutional.tsx";
import * as $$$$$$44 from "./sections/Institutional/OurStores.tsx";
import * as $$$$$$45 from "./sections/ItWorks.tsx";
import * as $$$$$$46 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$47 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$48 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$49 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$50 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$51 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$52 from "./sections/PopupNewsletter.tsx";
import * as $$$$$$53 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$54 from "./sections/Product/NotFound.tsx";
import * as $$$$$$55 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$56 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$57 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$58 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$59 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$60 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$61 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$62 from "./sections/ProxyIframe.tsx";
import * as $$$$$$63 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$64 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$65 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$3,
    "site/loaders/extensions/PDPCollectionFlags.ts": $$$4,
    "site/loaders/extensions/PDPColorsNew.ts": $$$5,
    "site/loaders/extensions/PLPCollectionFlags.ts": $$$6,
    "site/loaders/extensions/ProductColorSimilars.ts": $$$7,
    "site/loaders/extensions/ProductShelfCollectionsFlags.ts": $$$8,
    "site/loaders/icons.ts": $$$9,
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/List/Sections.tsx": $$$1,
    "site/loaders/MenuInstitucionalLoader.tsx": $$$2,
    "site/loaders/ourStores.ts": $$$10,
    "site/loaders/productRecommendations.ts": $$$11,
    "site/loaders/productSuggestions.ts": $$$12,
    "site/loaders/sizebay.ts": $$$13,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Benefits.tsx": $$$$$$1,
    "site/sections/Cards/CardShowcase.tsx": $$$$$$2,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$3,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$4,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$5,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$6,
    "site/sections/Cards/ProductShowcase.tsx": $$$$$$7,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$8,
    "site/sections/Category/CategoryList.tsx": $$$$$$9,
    "site/sections/Component.tsx": $$$$$$10,
    "site/sections/Content/Banner.tsx": $$$$$$11,
    "site/sections/Content/Benefits.tsx": $$$$$$12,
    "site/sections/Content/BlogPosts.tsx": $$$$$$13,
    "site/sections/Content/CallToAction.tsx": $$$$$$14,
    "site/sections/Content/Faq.tsx": $$$$$$15,
    "site/sections/Content/Features.tsx": $$$$$$16,
    "site/sections/Content/Hero.tsx": $$$$$$17,
    "site/sections/Content/ImageSection.tsx": $$$$$$18,
    "site/sections/Content/Intro.tsx": $$$$$$19,
    "site/sections/Content/Logos.tsx": $$$$$$20,
    "site/sections/Content/Partners.tsx": $$$$$$21,
    "site/sections/Content/RichText.tsx": $$$$$$22,
    "site/sections/Content/Table.tsx": $$$$$$23,
    "site/sections/Content/Testimonials.tsx": $$$$$$24,
    "site/sections/Content/Text.tsx": $$$$$$25,
    "site/sections/Content/TextWithImage.tsx": $$$$$$26,
    "site/sections/Footer.tsx": $$$$$$27,
    "site/sections/Footer/Footer.tsx": $$$$$$28,
    "site/sections/Gallery.tsx": $$$$$$29,
    "site/sections/Header/Header.tsx": $$$$$$30,
    "site/sections/Images/BannerGrid.tsx": $$$$$$31,
    "site/sections/Images/BannerWithLink.tsx": $$$$$$32,
    "site/sections/Images/Carousel.tsx": $$$$$$33,
    "site/sections/Images/ImageGallery.tsx": $$$$$$34,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$35,
    "site/sections/Institutional/AboutUs.tsx": $$$$$$36,
    "site/sections/Institutional/Breadcrumb.tsx": $$$$$$37,
    "site/sections/Institutional/ImageCard.tsx": $$$$$$38,
    "site/sections/Institutional/InstitucionalIndiqueForm.tsx": $$$$$$39,
    "site/sections/Institutional/InstitucionalPage.tsx": $$$$$$40,
    "site/sections/Institutional/InstitucionalPageIframe.tsx": $$$$$$41,
    "site/sections/Institutional/InstitucionalThereeImages.tsx": $$$$$$42,
    "site/sections/Institutional/Institutional.tsx": $$$$$$43,
    "site/sections/Institutional/OurStores.tsx": $$$$$$44,
    "site/sections/ItWorks.tsx": $$$$$$45,
    "site/sections/Links/LinkTree.tsx": $$$$$$46,
    "site/sections/Links/Shortcuts.tsx": $$$$$$47,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$48,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$49,
    "site/sections/Miscellaneous/Slide.tsx": $$$$$$50,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$51,
    "site/sections/PopupNewsletter.tsx": $$$$$$52,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$53,
    "site/sections/Product/NotFound.tsx": $$$$$$54,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$55,
    "site/sections/Product/ProductDetails.tsx": $$$$$$56,
    "site/sections/Product/ProductShelf.tsx": $$$$$$57,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$58,
    "site/sections/Product/SearchResult.tsx": $$$$$$59,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$60,
    "site/sections/Product/Wishlist.tsx": $$$$$$61,
    "site/sections/ProxyIframe.tsx": $$$$$$62,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$63,
    "site/sections/Social/WhatsApp.tsx": $$$$$$64,
    "site/sections/Theme/Theme.tsx": $$$$$$65,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
